//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class COReplacementOSBEntities : DbContext
    {
        public COReplacementOSBEntities()
            : base("name=COReplacementOSBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Student_Test> Student_Test { get; set; }
        public virtual DbSet<stdlogin> stdlogins { get; set; }
    
        public virtual int sp_student_test(string name, string address, string @class, ObjectParameter id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var classParameter = @class != null ?
                new ObjectParameter("class", @class) :
                new ObjectParameter("class", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_student_test", nameParameter, addressParameter, classParameter, id);
        }
    
        public virtual ObjectResult<sp_studnt_view_Result> sp_studnt_view()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_studnt_view_Result>("sp_studnt_view");
        }
    
        public virtual int sp_updatestudent(Nullable<int> stdid, string name, string address, string @class)
        {
            var stdidParameter = stdid.HasValue ?
                new ObjectParameter("stdid", stdid) :
                new ObjectParameter("stdid", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var classParameter = @class != null ?
                new ObjectParameter("class", @class) :
                new ObjectParameter("class", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_updatestudent", stdidParameter, nameParameter, addressParameter, classParameter);
        }
    }
}
